-- quotes.lua
-- Auto-generated by Rainmeter Quote Skin Generator

quotes = {
  { text="Enjoy the butterflies. Enjoy being naive. Enjoy the nerves, the pressure, people not knowing your name, all that stuff.", by="Daniel Ricciardo DR3", font="Segoe Script", color={255,255,255}, align="left", byAlign="right" },
  { text="Left Quotre", by="Left", font="Segoe Script", color={255,255,255}, align="left", byAlign="left" },
  { text="Right Quote", by="Right", font="Segoe Script", color={255,255,255}, align="right", byAlign="right" },
  { text="Mixed Quote", by="Mixed", font="Segoe Script", color={255,255,255}, align="left", byAlign="right" },
}

local STATE_FILE = nil

local function safeNumber(v, fallback)
  local n = tonumber(v)
  if n == nil then return fallback end
  return n
end

local function nQuotes()
  return (type(quotes) == "table") and #quotes or 0
end

local function trim(s)
  local t = s or ""
  t = t:gsub("^%s+", "")
  t = t:gsub("%s+$", "")
  return t
end

local function splitCSVInts(s)
  s = trim(s)
  if s == "" then return {} end
  local out = {}
  for part in string.gmatch(s, "([^,]+)") do
    local n = tonumber(trim(part))
    if n ~= nil then table.insert(out, n) end
  end
  return out
end

local function joinCSVInts(t)
  local parts = {}
  for i = 1, #t do
    parts[#parts + 1] = tostring(t[i])
  end
  return table.concat(parts, ",")
end

local function shuffle(t)
  for i = #t, 2, -1 do
    local j = math.random(i)
    t[i], t[j] = t[j], t[i]
  end
end

local function safeColor(c)
  if type(c) == "table" then
    local r = math.floor(safeNumber(c[1], 255))
    local g = math.floor(safeNumber(c[2], 255))
    local b = math.floor(safeNumber(c[3], 255))
    if r < 0 then r = 0 elseif r > 255 then r = 255 end
    if g < 0 then g = 0 elseif g > 255 then g = 255 end
    if b < 0 then b = 0 elseif b > 255 then b = 255 end
    return r, g, b
  end
  return 255, 255, 255
end

local function toTopAlign(a, default)
  a = (a or default or "left"):lower()
  if a == "center" then return "CenterTop" end
  if a == "right" then return "RightTop" end
  return "LeftTop"
end

local function computeX(alignTop, baseX, width)
  if alignTop == "RightTop" then return baseX + width end
  if alignTop == "CenterTop" then return baseX + (width / 2) end
  return baseX
end

local function positionAuthorBelowQuote()
  local quoteY = safeNumber(SKIN:GetVariable("QuoteY"), 20)
  local gap = safeNumber(SKIN:GetVariable("Gap"), 12)

  SKIN:Bang("!UpdateMeter", "MeterQuote")
  SKIN:Bang("!Redraw")

  local quoteMeter = SKIN:GetMeter("MeterQuote")
  local quoteHeight = 0
  if quoteMeter ~= nil then
    quoteHeight = quoteMeter:GetH()
  end

  local authorY = quoteY + quoteHeight + gap
  SKIN:Bang("!SetOption", "MeterAuthor", "Y", tostring(authorY))
end

local function applyQuote(idx)
  local baseX = safeNumber(SKIN:GetVariable("QuoteX"), 20)
  local width = safeNumber(SKIN:GetVariable("QuoteW"), 520)

  if idx <= 0 or nQuotes() <= 0 then
    SKIN:Bang("!SetVariable", "QuoteText", "No quotes found.")
    SKIN:Bang("!SetVariable", "QuoteAuthor", "")
    SKIN:Bang("!SetVariable", "QuoteFont", SKIN:GetVariable("DefaultFont") or "Segoe UI")
    SKIN:Bang("!SetVariable", "QuoteSize", SKIN:GetVariable("DefaultSize") or "18")
    SKIN:Bang("!SetVariable", "QuoteColor", SKIN:GetVariable("DefaultColor") or "255,255,255")
    SKIN:Bang("!SetVariable", "QuoteAlign", "LeftTop")
    SKIN:Bang("!SetVariable", "QuoteByAlign", "LeftTop")
    SKIN:Bang("!SetVariable", "QuoteXPos", tostring(baseX))
    SKIN:Bang("!SetVariable", "ByXPos", tostring(baseX))
  else
    local q = quotes[idx] or quotes[1]
    local text = q.text or ""
    local by = q.by or ""
    local font = q.font or (SKIN:GetVariable("DefaultFont") or "Segoe UI")
    local r, g, b = safeColor(q.color)

    local quoteAlignTop = toTopAlign(q.align, "left")
    local byAlignTop = toTopAlign(q.byAlign, "left")

    local quoteXPos = computeX(quoteAlignTop, baseX, width)
    local byXPos = computeX(byAlignTop, baseX, width)

    SKIN:Bang("!SetVariable", "QuoteText", text)
    SKIN:Bang("!SetVariable", "QuoteAuthor", by)
    SKIN:Bang("!SetVariable", "QuoteFont", font)
    SKIN:Bang("!SetVariable", "QuoteSize", SKIN:GetVariable("DefaultSize") or "18")
    SKIN:Bang("!SetVariable", "QuoteColor", string.format("%d,%d,%d", r, g, b))
    SKIN:Bang("!SetVariable", "QuoteAlign", quoteAlignTop)
    SKIN:Bang("!SetVariable", "QuoteByAlign", byAlignTop)
    SKIN:Bang("!SetVariable", "QuoteXPos", tostring(quoteXPos))
    SKIN:Bang("!SetVariable", "ByXPos", tostring(byXPos))
  end

  positionAuthorBelowQuote()
  SKIN:Bang("!UpdateMeter", "MeterQuote")
  SKIN:Bang("!UpdateMeter", "MeterAuthor")
  SKIN:Bang("!Redraw")
end

local function todayStamp()
  return os.date("%Y%m%d")
end

local function writeState(lastDay, bagStr, currentIdx)
  SKIN:Bang("!WriteKeyValue", "Variables", "LastDayStamp", tostring(lastDay or "0"), STATE_FILE)
  SKIN:Bang("!WriteKeyValue", "Variables", "Bag", bagStr or "", STATE_FILE)
  SKIN:Bang("!WriteKeyValue", "Variables", "CurrentIndex", tostring(currentIdx or "0"), STATE_FILE)
end

local function loadBagOrRefill()
  local n = nQuotes()
  if n <= 0 then return {} end

  local bagVar = SKIN:GetVariable("Bag") or ""
  local bag = splitCSVInts(bagVar)

  -- Remove invalid indices (in case quote count changed)
  local cleaned = {}
  for i = 1, #bag do
    local v = bag[i]
    if v >= 1 and v <= n then cleaned[#cleaned + 1] = v end
  end
  bag = cleaned

  if #bag == 0 then
    for i = 1, n do bag[#bag + 1] = i end
    shuffle(bag)
  end

  return bag
end

local function popNextIndex()
  local n = nQuotes()
  if n <= 0 then return 0 end

  local bag = loadBagOrRefill()
  local idx = bag[#bag]
  bag[#bag] = nil

  local bagStr = joinCSVInts(bag)
  local day = todayStamp()

  SKIN:Bang("!SetVariable", "Bag", bagStr)
  SKIN:Bang("!SetVariable", "CurrentIndex", tostring(idx))
  SKIN:Bang("!SetVariable", "LastDayStamp", tostring(day))

  writeState(day, bagStr, idx)
  return idx
end

local function showNewQuote(reason)
  local idx = popNextIndex()
  applyQuote(idx)
end

function Initialize()
  STATE_FILE = SKIN:GetVariable("@") .. "State.inc"

  local n = nQuotes()
  if n <= 0 then
    applyQuote(0)
    return
  end

  -- Seed randomness once per load/refresh
  math.randomseed(os.time())
  math.random(); math.random(); math.random()

  -- Always show a new quote on refresh/reload
  showNewQuote("refresh")
end

function Update()
  -- Called every skin update tick.
  -- If the day changed since last recorded day, advance automatically.
  local stored = tostring(SKIN:GetVariable("LastDayStamp") or "0")
  local now = todayStamp()

  if stored ~= now then
    showNewQuote("daychange")
  end

  return 0
end